<?php

namespace Database\Factories;

use App\Models\EmployeeProfile;
use App\Models\JobRole;
use App\Models\LeavePolicy;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<EmployeeProfile>
 */
class EmployeeProfileFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'job_role_id' => JobRole::factory(),
            'leave_policy_id' => LeavePolicy::first()?->id ?? LeavePolicy::factory(),
            'base_salary' => fake()->numberBetween(30000, 150000),
            'employee_id' => null, // Will be generated by model boot if left null
            'joining_date' => fake()->dateTimeBetween('-2 years', 'now'),
            'phone' => fake()->phoneNumber(),
            'address' => fake()->address(),
            'gender' => fake()->randomElement(['Male', 'Female', 'Other']),
            'birthday' => fake()->dateTimeBetween('-50 years', '-20 years'),
            'marital_status' => fake()->randomElement(['Single', 'Married', 'Divorced', 'Widowed']),
        ];
    }
}
